
const KEY="HM_FINAL_V1";
const D={connected:false,wallet:"",holder:false,holdingDays:0,completed:[],settings:{mission:10,mult:2,holding:100,days:30},projects:[
{id:"northstar",name:"Northstar Labs",symbol:"NORTH",desc:"Open-source tooling team looking for real community testers."},
{id:"arcfield",name:"Arcfield",symbol:"ARC",desc:"A new on-chain product running a community discovery campaign."},
{id:"signallab",name:"SignalLab",symbol:"SIG",desc:"Practical Web3 research and signal tools."}],
missions:[
{id:"m1",project:"Northstar Labs",title:"Follow Northstar on X",type:"X Follow",xp:10,url:"https://x.com"},
{id:"m2",project:"Northstar Labs",title:"Repost the launch post",type:"X Repost",xp:10,url:"https://x.com"},
{id:"m3",project:"Arcfield",title:"Join the Arcfield Discord",type:"Discord",xp:15,url:"https://discord.com"},
{id:"m4",project:"Arcfield",title:"Comment your wallet on X",type:"X Comment",xp:20,url:"https://x.com"},
{id:"m5",project:"SignalLab",title:"Join the community",type:"Discord",xp:10,url:"https://discord.com"},
{id:"m6",project:"SignalLab",title:"Follow SignalLab on X",type:"X Follow",xp:10,url:"https://x.com"}]};
function S(){let s=JSON.parse(localStorage.getItem(KEY)||"null");if(!s){s=structuredClone(D);localStorage.setItem(KEY,JSON.stringify(s))}return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function total(s){return s.holdingDays*s.settings.holding+s.missions.filter(m=>s.completed.includes(m.id)).reduce((a,m)=>a+(s.holder?m.xp*s.settings.mult:m.xp),0)}
function toast(x){let t=document.querySelector("#toast");if(t){t.textContent=x;t.classList.add("on");setTimeout(()=>t.classList.remove("on"),2200)}}
function shell(){document.body.insertAdjacentHTML("afterbegin",'<header class="top"><div class="wrap"><a class="brand" href="/"><span class="mark"><span>HM</span></span>HOOD MEMORY</a><nav class="nav"><a href="/">Home</a><a href="/discover/">Discover</a><a href="/missions/">Missions</a><a href="/projects/">Projects</a><a href="/leaderboard/">Leaderboard</a><a href="/rewards/">Rewards</a><a href="/docs/">Docs</a><a class="wallet" href="/dashboard/">Profile</a></nav><button class="menu" id="menu">☰</button></div></header><div class="mobile" id="mobile"><a href="/">Home</a><a href="/discover/">Discover</a><a href="/missions/">Missions</a><a href="/projects/">Projects</a><a href="/leaderboard/">Leaderboard</a><a href="/rewards/">Rewards</a><a href="/docs/">Docs</a><a href="/dashboard/">Profile</a></div><div class="toast" id="toast"></div>');
document.querySelector("#menu").onclick=()=>document.querySelector("#mobile").classList.toggle("on");document.body.insertAdjacentHTML("beforeend",'<footer class="foot wrap"><span>HOOD MEMORY © 2026</span><span>Test. Earn. Remember.</span><a href="/admin/">Admin</a></footer>')}
function connect(){let s=S(),w=prompt("Paste an EVM wallet address to preview verification:","0x1234567890abcdef");if(!w)return;s.wallet=w.trim();s.connected=true;s.holder=/^0x[0-9a-fA-F]{10,}$/.test(s.wallet);s.holdingDays=s.holder?Math.max(1,s.holdingDays):0;save(s);toast(s.holder?"Holder access unlocked":"Public profile created");setTimeout(()=>location.reload(),450)}
function projectCard(p){return '<article class="card"><div class="art">'+esc(p.symbol)+'</div><span class="tag live">LIVE</span><h3 style="margin-top:10px">'+esc(p.name)+'</h3><p>'+esc(p.desc)+'</p><div class="actions"><a class="btn" href="/projects/'+p.id+'/">View project</a><a class="btn" href="/missions/">Missions</a></div></article>'}
function missionCard(m,s){let done=s.completed.includes(m.id),v=s.holder?Math.round(m.xp*s.settings.mult):m.xp;return '<div class="card mission"><div class="missionleft"><div class="icon">'+esc(m.type.slice(0,2).toUpperCase())+'</div><div><div class="meta"><span>'+esc(m.project)+'</span><span class="tag">'+esc(m.type)+'</span></div><h3>'+esc(m.title)+'</h3><div class="xp">+'+v+' XP '+(s.holder?"· HOLDER BONUS":"")+'</div></div></div><div class="actions">'+(done?'<span class="tag live">COMPLETED</span>':'<button class="btn primary complete" data-id="'+m.id+'">Complete</button>')+'</div></div>'}
function bind(){document.querySelectorAll(".complete").forEach(b=>b.onclick=()=>{let s=S(),m=s.missions.find(x=>x.id===b.dataset.id);if(!m||s.completed.includes(m.id))return;if(m.url)window.open(m.url,"_blank");s.completed.push(m.id);save(s);toast("Mission completed");setTimeout(()=>location.reload(),450)})}

function renderPage(p){
shell();let s=S(),a=document.querySelector("#app");
if(p==="home"){a.innerHTML=`<section class="hero"><div><div class="k">Robinhood Chain · 1,111 Access NFTs</div><h1>THE NETWORK<br><span style="color:var(--cyan)">REMEMBERS.</span></h1><p class="lead">HOOD MEMORY is a public mission network. Projects publish campaigns; users complete them and earn XP. Everyone can participate. NFT holders receive boosted mission XP and daily holding XP.</p><div class="actions"><a class="btn primary" href="/discover/">Explore Discover</a><a class="btn" href="/mint/">Mint Access NFT</a><a class="btn" href="/missions/">Open Missions</a></div><div class="notice" style="margin-top:20px">Public access is open. <b>NFT holders earn boosted mission XP + daily holding XP.</b></div></div><div class="core"><div class="orb"></div><div class="orb"></div><div class="cube"></div><div class="coretext">HOOD MEMORY</div></div></section><section class="section"><div class="head"><div><div class="k">The model</div><h2>Two XP layers.</h2></div><p>Mission XP measures participation. Holder XP rewards ownership and holding.</p></div><div class="statrow"><div class="stat"><span>Mission XP</span><b>10+</b></div><div class="stat"><span>Holder bonus</span><b>2×</b></div><div class="stat"><span>Holding XP/day</span><b>100</b></div><div class="stat"><span>Season</span><b>30D</b></div></div></section><section class="section"><div class="head"><div><div class="k">Discover</div><h2>Projects live now.</h2></div><a class="btn" href="/discover/">View all</a></div><div class="grid">'+s.projects.map(projectCard).join("")+'</div></section>`}
else if(p==="discover"){a.innerHTML='<section class="page"><div class="k">Discover</div><h1>FIND YOUR NEXT<br><span style="color:var(--cyan)">MISSION.</span></h1><p>Curated project campaigns: X Follow, Repost, Comment, Discord and more.</p><div class="filters"><input class="input" id="q" placeholder="Search projects..."><span class="tag live">PUBLIC ACCESS</span><span class="tag">HOLDER XP BOOST</span></div><div class="grid" id="g"></div></section>';let g=document.querySelector("#g");function r(){let q=document.querySelector("#q").value.toLowerCase();g.innerHTML=s.projects.filter(x=>(x.name+x.desc).toLowerCase().includes(q)).map(projectCard).join("")}document.querySelector("#q").oninput=r;r()}
else if(p==="mint"){a.innerHTML='<section class="page"><div class="k">Mainnet Mint</div><h1>OWN THE<br><span style="color:var(--cyan)">MEMORY.</span></h1><p>1,111 HOOD MEMORY NFTs on Robinhood Chain Mainnet.</p><div class="detail"><div class="card"><div class="k">Collection</div><h2>1,111</h2><p>WL: FREE* · Public: ETH</p><div class="notice">The real mint contract is the next integration. This package does not send real transactions.</div></div><div class="card"><div class="k">Wallet</div><h3>Verify access</h3><p>Preview holder/public flow with an EVM address.</p><button class="btn primary" id="c">Connect / Verify</button></div></div></section>';document.querySelector("#c").onclick=connect}
else if(p==="missions"){a.innerHTML='<section class="page"><div class="k">Mission Board</div><h1>COMPLETE.<br><span style="color:var(--lime)">EARN XP.</span></h1><p>New campaigns can be added every day.</p><div class="statrow"><div class="stat"><span>Status</span><b>'+ (s.holder?"HOLDER":"PUBLIC") +'</b></div><div class="stat"><span>Completed</span><b>'+s.completed.length+'</b></div><div class="stat"><span>Total XP</span><b>'+total(s)+'</b></div><div class="stat"><span>Holding XP/day</span><b>'+ (s.holder?s.settings.holding:0) +'</b></div></div><div style="display:grid;gap:12px;margin-top:20px">'+s.missions.map(m=>missionCard(m,s)).join("")+'</div></section>';bind()}
else if(p==="projects"){a.innerHTML='<section class="page"><div class="k">Projects</div><h1>BUILDERS<br><span style="color:var(--violet)">IN THE NETWORK.</span></h1><p>Projects use HOOD MEMORY to distribute measurable community campaigns.</p><div class="grid">'+s.projects.map(projectCard).join("")+'</div></section>'}
else if(p.startsWith("project-")){let id=p.slice(8),pr=s.projects.find(x=>x.id===id)||s.projects[0],ms=s.missions.filter(x=>x.project===pr.name);a.innerHTML='<section class="page"><div class="k">Project</div><h1>'+esc(pr.name)+'<br><span style="color:var(--cyan)">'+esc(pr.symbol)+'</span></h1><p>'+esc(pr.desc)+'</p><div class="actions"><a class="btn primary" href="/missions/">Open campaign</a><a class="btn" href="/discover/">Back</a></div><section class="section"><div class="head"><h2>Live missions</h2><span class="tag live">'+ms.length+' ACTIVE</span></div><div style="display:grid;gap:12px">'+ms.map(m=>missionCard(m,s)).join("")+'</div></section></section>';bind()}
else if(p==="submit"){a.innerHTML='<section class="page"><div class="k">For Projects</div><h1>BRING YOUR<br><span style="color:var(--cyan)">MISSION.</span></h1><p>Submit campaigns for free during the initial phase. Admin reviews and publishes approved campaigns.</p><div class="card"><form id="f" class="form"><div class="field"><label>Project name</label><input class="input" name="project" required></div><div class="field"><label>Symbol</label><input class="input" name="symbol" required></div><div class="field full"><label>Description</label><textarea name="desc" rows="4" required></textarea></div><div class="field"><label>Mission</label><input class="input" name="mission" required></div><div class="field"><label>Type</label><select class="select" name="type"><option>X Follow</option><option>X Repost</option><option>X Comment</option><option>Discord</option></select></div><div class="field"><label>Action URL</label><input class="input" name="url" required></div><div class="field"><label>Base XP</label><input class="input" name="xp" type="number" value="10"></div><div class="field full"><button class="btn primary">Submit campaign</button></div></form></div></section>';document.querySelector("#f").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),base=+f.get("xp")||10;s.projects.push({id:"p"+Date.now(),name:f.get("project"),symbol:f.get("symbol"),desc:f.get("desc")});s.missions.push({id:"m"+Date.now(),project:f.get("project"),title:f.get("mission"),type:f.get("type"),xp:base,url:f.get("url")});save(s);location.href="/admin/"}}
else if(p==="dashboard"){a.innerHTML='<section class="page"><div class="k">Profile</div><h1>YOUR MEMORY<br><span style="color:var(--lime)">PROFILE.</span></h1><div id="d"></div></section>';let d=document.querySelector("#d");d.innerHTML=s.connected?'<div class="card"><div class="profile"><div class="avatar">HM</div><div><span class="tag '+(s.holder?"live":"")+'">'+(s.holder?"NFT HOLDER":"PUBLIC USER")+'</span><h2>'+esc(s.wallet)+'</h2><p>Season 01</p></div></div><div class="statrow" style="margin-top:20px"><div class="stat"><span>Total XP</span><b>'+total(s)+'</b></div><div class="stat"><span>Completed</span><b>'+s.completed.length+'</b></div><div class="stat"><span>Holding days</span><b>'+s.holdingDays+'</b></div><div class="stat"><span>Daily holder XP</span><b>'+ (s.holder?s.settings.holding:0) +'</b></div></div><div class="actions"><a class="btn primary" href="/missions/">Missions</a><a class="btn" href="/xp/">XP History</a><button class="btn danger" id="out">Disconnect</button></div></div>':'<div class="card lock"><b>◈</b><h2>Connect your wallet</h2><p>Create a public profile and verify holder access.</p><button class="btn primary" id="c">Connect wallet</button></div>';document.querySelector("#c")?.addEventListener("click",connect);document.querySelector("#out")?.addEventListener("click",()=>{s.connected=false;s.wallet="";s.holder=false;save(s);location.reload()})}
else if(p==="xp"){let rows=s.missions.filter(m=>s.completed.includes(m.id));a.innerHTML='<section class="page"><div class="k">XP Ledger</div><h1>EVERY ACTION<br><span style="color:var(--lime)">COUNTS.</span></h1><div class="statrow"><div class="stat"><span>Total</span><b>'+total(s)+'</b></div><div class="stat"><span>Holding</span><b>'+s.holdingDays*s.settings.holding+'</b></div><div class="stat"><span>Mission</span><b>'+rows.reduce((q,m)=>q+(s.holder?m.xp*s.settings.mult:m.xp),0)+'</b></div><div class="stat"><span>Season</span><b>01</b></div></div><div class="card" style="margin-top:18px"><table class="table"><tr><th>Mission</th><th>Project</th><th>XP</th></tr>'+rows.map(m=>'<tr><td>'+esc(m.title)+'</td><td>'+esc(m.project)+'</td><td class="xp">+'+(s.holder?m.xp*s.settings.mult:m.xp)+'</td></tr>').join("")+'</table></div></section>'}
else if(p==="leaderboard"){let arr=[{w:"0x8F2...91A",x:4820,h:1},{w:"0x31A...F02",x:4410,h:1},{w:"0xB77...E10",x:3970,h:1},{w:"0xA04...C21",x:2860,h:0}];if(s.connected)arr.push({w:s.wallet,x:total(s),h:s.holder});arr.sort((x,y)=>y.x-x.x);a.innerHTML='<section class="page"><div class="k">Season 01</div><h1>LEADERBOARD<br><span style="color:var(--violet)">OF MEMORY.</span></h1><div class="card"><table class="table"><tr><th>#</th><th>Wallet</th><th>Status</th><th>XP</th></tr>'+arr.map((r,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(r.w)+'</td><td>'+(r.h?'<span class="tag live">HOLDER</span>':'<span class="tag">PUBLIC</span>')+'</td><td class="xp">'+r.x+'</td></tr>').join("")+'</table></div></section>'}
else if(p==="rewards"){a.innerHTML='<section class="page"><div class="k">Rewards</div><h1>XP TODAY.<br><span style="color:var(--cyan)">TOKEN LATER.</span></h1><p>Season 01 is planned for 30 days. XP will be snapshotted after the season. Final HMEMORY allocation rules will be published before the snapshot.</p><div class="grid"><div class="card"><div class="k">Season</div><h3>30 Days</h3><p>Participate and accumulate verified XP.</p></div><div class="card"><div class="k">Holder</div><h3>Daily XP</h3><p>NFT holders receive the configured holding reward.</p></div><div class="card"><div class="k">HMEMORY</div><h3>Coming Soon</h3><p>Token contract and claim mechanism will be announced separately.</p></div></div></section>'}
else if(p==="docs"){a.innerHTML='<section class="page"><div class="k">Documentation</div><h1>HOW HOOD MEMORY<br><span style="color:var(--cyan)">WORKS.</span></h1><div class="grid"><div class="card"><h3>01 · NFT</h3><p>1,111 NFTs form the holder reward/access layer.</p></div><div class="card"><h3>02 · Discover</h3><p>Projects publish campaigns with admin approval.</p></div><div class="card"><h3>03 · Missions</h3><p>X Follow, Repost, Comment, Discord and future action types.</p></div><div class="card"><h3>04 · XP</h3><p>Public base XP; holders receive boosted mission XP and daily holding XP.</p></div><div class="card"><h3>05 · Season</h3><p>Season 01 is planned for 30 days followed by an XP snapshot.</p></div><div class="card"><h3>06 · Production</h3><p>Supabase, wallet verification and secure admin auth are connected later.</p></div></div></section>'}
else if(p==="profile"){a.innerHTML='<section class="page"><div class="k">Public Profile</div><h1>MEMORY<br><span style="color:var(--violet)">IDENTITY.</span></h1><div class="card"><div class="profile"><div class="avatar">HM</div><div><span class="tag '+(s.holder?"live":"")+'">'+(s.holder?"HOLDER":"PUBLIC")+'</span><h2>'+(s.connected?esc(s.wallet):"Not connected")+'</h2><p>'+total(s)+' XP · Season 01</p></div></div><div class="actions"><a class="btn primary" href="/dashboard/">Dashboard</a><a class="btn" href="/leaderboard/">Leaderboard</a></div></div></section>'}
else if(p==="admin"){a.innerHTML='<section class="page"><div class="k">Control Room</div><h1>ADMIN<br><span style="color:var(--pink)">COMMAND.</span></h1><div class="admin"><aside class="card side"><a href="#m">Missions</a><a href="#x">XP Settings</a><a href="#s">Season</a></aside><div><section id="m" class="card"><div class="k">Mission Manager</div><table class="table"><tr><th>Mission</th><th>Project</th><th>XP</th><th></th></tr>'+s.missions.map(m=>'<tr><td>'+esc(m.title)+'</td><td>'+esc(m.project)+'</td><td>'+m.xp+'/'+m.xp*s.settings.mult+'</td><td><button class="btn danger del" data-id="'+m.id+'">Delete</button></td></tr>').join("")+'</table></section><section id="x" class="card" style="margin-top:15px"><div class="k">XP Settings</div><div class="form"><div class="field"><label>Mission XP</label><input class="input" id="mx" value="'+s.settings.mission+'"></div><div class="field"><label>Holder multiplier</label><input class="input" id="mm" value="'+s.settings.mult+'"></div><div class="field"><label>Holding XP/day</label><input class="input" id="hx" value="'+s.settings.holding+'"></div><div class="field"><label>Season days</label><input class="input" id="sd" value="'+s.settings.days+'"></div><div class="field full"><button class="btn primary" id="save">Save settings</button></div></div></section><section id="s" class="card" style="margin-top:15px"><div class="k">Season 01</div><h2>30 days</h2><div class="actions"><a class="btn primary" href="/submit/">Add campaign</a><button class="btn danger" id="reset">Reset local data</button></div></section></div></div></section>';document.querySelectorAll(".del").forEach(b=>b.onclick=()=>{s.missions=s.missions.filter(m=>m.id!==b.dataset.id);save(s);location.reload()});document.querySelector("#save").onclick=()=>{s.settings.mission=+document.querySelector("#mx").value||10;s.settings.mult=+document.querySelector("#mm").value||2;s.settings.holding=+document.querySelector("#hx").value||100;s.settings.days=+document.querySelector("#sd").value||30;save(s);toast("XP settings saved")};document.querySelector("#reset").onclick=()=>{localStorage.removeItem(KEY);location.reload()}}
else if(p.startsWith("mission-")){let m=s.missions.find(x=>x.id===p.slice(8))||s.missions[0];a.innerHTML='<section class="page"><div class="k">'+esc(m.project)+'</div><h1>'+esc(m.title)+'</h1><p>'+esc(m.type)+' · +'+(s.holder?m.xp*s.settings.mult:m.xp)+' XP</p><div class="actions"><button class="btn primary complete" data-id="'+m.id+'">Complete mission</button><a class="btn" href="/missions/">Back</a></div><div class="notice" style="margin-top:20px">Production verification will validate proof before permanent XP credit.</div></section>';bind()}
}
